import '../models/course.dart';

/// Jadwal Semester V berdasarkan tabel yang diberikan.
/// Waktu mengikuti jam lokal Indonesia (WIB) untuk tampilan aplikasi.
const List<Course> courses = [
  Course(
    id: 1,
    name: 'Pemrograman Mobile',
    code: 'TKR14154',
    sks: 3,
    lecturer: 'Muh Pauzan, S.Si, M.Sc',
    day: 'Selasa',
    weekday: DateTime.tuesday,
    start: '13:00',
    end: '15:30',
    room: 'E/B',
  ),
  Course(
    id: 2,
    name: 'Programmable Logic Control (PLC)',
    code: 'TKR14149',
    sks: 2,
    lecturer: 'Denny Arief Rusamsi, S.T, M.T',
    day: 'Selasa',
    weekday: DateTime.tuesday,
    start: '15:30',
    end: '17:10',
    room: 'B',
  ),
  Course(
    id: 3,
    name: 'Sistem Waktu Nyata',
    code: 'TKR14150',
    sks: 2,
    lecturer: 'Dr. Ir. Taufik Hidayat, S.Kom, M.T., IPP',
    day: 'Rabu',
    weekday: DateTime.wednesday,
    start: '09:40',
    end: '11:20',
    room: 'E2',
  ),
  Course(
    id: 4,
    name: 'Pengolahan Sinyal Digital',
    code: 'TKR14150',
    sks: 2,
    lecturer: 'Dr. Ir. Taufik Hidayat, S.Kom, M.T., IPP',
    day: 'Rabu',
    weekday: DateTime.wednesday,
    start: '11:20',
    end: '13:00',
    room: 'E2',
  ),
  Course(
    id: 5,
    name: 'Jaringan Sensor Nirkabel',
    code: 'TKR14156',
    sks: 2,
    lecturer: 'Denny Arief Rusamsi, S.T, M.T',
    day: 'Kamis',
    weekday: DateTime.thursday,
    start: '10:00',
    end: '11:40',
    room: 'B',
  ),
  Course(
    id: 6,
    name: 'Desain dan Aplikasi IoT',
    code: 'TKR12152',
    sks: 3,
    lecturer: 'Muh Pauzan, S.Si, M.Sc',
    day: 'Kamis',
    weekday: DateTime.thursday,
    start: '13:00',
    end: '15:30',
    room: 'D',
  ),
  Course(
    id: 7,
    name: 'Robotika',
    code: 'TKR14153',
    sks: 3,
    lecturer: 'Muh Pauzan, S.Si, M.Sc',
    day: 'Jumat',
    weekday: DateTime.friday,
    start: '08:00',
    end: '10:30',
    room: 'B',
  ),
  Course(
    id: 8,
    name: 'Pemrograman Website',
    code: 'TKR14155',
    sks: 3,
    lecturer: 'Ferry Kurniawan Margana, M.Kom',
    day: 'Jumat',
    weekday: DateTime.friday,
    start: '13:00',
    end: '15:30',
    room: 'B',
  ),
];
